FROM python:3.12-slim

WORKDIR /app

COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV DB_FILE="/tmp/test.db"
ENV PYTHONUNBUFFERED=1

CMD ["pytest", "--maxfail=1", "--disable-warnings", "-q"]
